name: Continuous Integration

on:
  pull_request:
    branches: ["master"]
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        working-directory: ./server
        run: pip install -r requirements.txt

      - name: Check Linter - Python
        uses: rickstaa/action-black@v1
        with:
          black_args: ". --check"
